// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAicRbzkm9nOYr9MCmjGigqkDEZkXFUoWM',
    appId: '1:551882827746:web:b541ac242ee86e63ee7bbb',
    messagingSenderId: '551882827746',
    projectId: 'bet-app-ee55d',
    authDomain: 'bet-app-ee55d.firebaseapp.com',
    storageBucket: 'bet-app-ee55d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwsRq_iwyVeuFj_iTv0O4ZxdkYaC8XAsM',
    appId: '1:551882827746:android:f2246812c6ff8987ee7bbb',
    messagingSenderId: '551882827746',
    projectId: 'bet-app-ee55d',
    storageBucket: 'bet-app-ee55d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiwn_z-eKrJz2FYGsbeu-1pVy7PXVlNtE',
    appId: '1:551882827746:ios:390cfc6429304fdfee7bbb',
    messagingSenderId: '551882827746',
    projectId: 'bet-app-ee55d',
    storageBucket: 'bet-app-ee55d.appspot.com',
    androidClientId: '551882827746-narmnjeovlcs2hku631skb2p3esalkfm.apps.googleusercontent.com',
    iosClientId: '551882827746-lif7olos09gpngmi1765fftage4l9e1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.betApp',
  );
}
